### ISSUE TITLE
Add checks to see if the add-on should activate

### ISSUE THREAD

**Issue by acorncom** [locks/ember-welcome-page#5]
It should only activate if all three of these checks return false:

 - [ ] Has an application.hbs been created?
 - [ ] Has an index.hbs been created?
 - [ ] Have any routes been created?

**Comment by acorncom** [comment]
@rwjblue you mentioned in https://github.com/ember-cli/ember-cli/pull/5501#issuecomment-187577657 that

> I'd like to see a ember-getting-started addon (added by default) that adds a separate Ember app mounted at /ember-getting-started (or some other non-conflicting path) and takes over / if no routes are present in Router.map or on disk. This would:

> - enable usage of a nice interactive getting started app when no routes/templates are present
> - enable usage of interactive guide when navigating to a specific URL (which could print to the console on initial ember serve or something)
> - remove extra boilerplate that is generated into ember-cli apps (the current presence of app/templates/application.hbs is very annoying to me every time I run ember init)

Would you be able to detail a bit more what you're thinking about how to detect `no routes ... on disk`?  I think I know how to detect the `Router.map` (or can figure it out), but not sure about the other.

Also, my current thought was to insert content via `contentFor` and not even have a route setup (more details here: https://github.com/locks/ember-welcome-page/blob/master/index.js#L19-L25)  Is that just incredibly ugly and not where you want to go at all? ;-)

**Comment by rwjblue** [comment]
Super simple detection:

```
var walkSync = require('walk-sync');
  var path = require('path');
  var fs = require('fs');

  var templateExtensions = app.registry.extensionsForType('template');
  var jsExtensions = app.registry.extensionsForType('js');
  var appFiles = walkSync(path.join(app.project.root, 'app'));
  var jsFiles = appFiles
        .filter(function(fileName) {
          var extension = path.extname(fileName).slice(1); // remove leading `.`

          return jsExtensions.indexOf(extension) > -1;
        });

  var templateFiles = appFiles
        .filter(function(fileName) {
          var extension = path.extname(fileName).slice(1); // remove leading `.`

          return templateExtensions.indexOf(extension) > -1;
        });

  var routeFiles = jsFiles
        .filter(function(fileName) {
          var baseName = path.basename(fileName);

          return baseName === 'route' || fileName.match(/^routes/);
        });

  var router = fs.readFileSync(path.join(app.project.root, 'app', 'router.js'), { encoding: 'utf8' });

  var hasTemplates = templateFiles.length > 0;
  var hasRoutes = routeFiles.length > 0;
  var hasRouterMapContents = router.match(/this\.route|this\.resource/);

  return !hasTemplates && !hasRoutes && !hasRouterMapContents;
```

We might have to specifically exclude `app/templates/application.hbs` for this to pass on a new app...
